const esbuild = require('esbuild');
const babel = require('@babel/core');
const fs = require('fs');
const path = require('path');

const lookerFixPlugin = {
  name: 'looker-fix',
  setup(build) {
    build.onLoad({ filter: /@looker\/components\/.*index\.js$/ }, async (args) => {
      const contents = await fs.promises.readFile(args.path, 'utf8');
      const modifiedContents = contents.replace(
        "export { theme, Theme } from '@looker/design-tokens';",
        "export { theme } from '@looker/design-tokens'; export const Theme = {};"
      ).replace(
        "export { theme, Theme } from \"@looker/design-tokens\";",
        "export { theme } from \"@looker/design-tokens\"; export const Theme = {};"
      );
      return {
        contents: modifiedContents,
        loader: 'js',
      };
    });
  },
};

async function build() {
  console.log('Building extension...');

  try {
    // 1. Bundle with esbuild targeting es2015
    const result = await esbuild.build({
      entryPoints: [path.join(__dirname, 'src/index.tsx')],
      bundle: true,
      write: false, // get output in memory
      minify: false, // don't minify yet so we can run Babel easily
      target: 'es2015',
      outfile: 'dist/month_end_filter.js',
      define: {
        'process.env.NODE_ENV': '"production"',
      },
      plugins: [lookerFixPlugin],
    });

    if (!result.outputFiles || result.outputFiles.length === 0) {
      throw new Error('No output files generated by esbuild.');
    }

    const originalCode = result.outputFiles[0].text;

    // 2. Run Babel to transpile any ES6/ESNext syntax (like spreads) down to ES5
    console.log('Transpiling with Babel to remove spread operators...');
    const babelResult = await babel.transformAsync(originalCode, {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              ie: '11', // Forces full ES5 compliance, including removing all spreads
            },
            modules: false,
          },
        ],
      ],
      compact: false,
    });

    let finalCode = babelResult.code;

    // 3. Make sure the output directory exists
    const distDir = path.join(__dirname, 'dist');
    if (!fs.existsSync(distDir)) {
      fs.mkdirSync(distDir, { recursive: true });
    }

    // 4. Verify no spread operators remain in the output
    // A spread operator in JS can be identified by the "..." sequence.
    // We check for any "..." that are followed by alphanumeric characters or symbols,
    // indicating spread syntax (e.g. "...x" or "...[") rather than ellipsis in a string.
    const containsSpread = /\.\.\.[a-zA-Z_$0-9\[\{]/.test(finalCode);
    if (containsSpread) {
      console.warn('WARNING: Spread operator (...) detected in the output bundle!');
      const matches = finalCode.match(/(\S{0,20}\.\.\.\S{0,20})/g);
      console.warn('Potential matches:', matches);
      process.exit(1); // Fail the build to ensure compatibility
    } else {
      console.log('Success: No spread operators detected in the output bundle.');
    }

    fs.writeFileSync(path.join(distDir, 'month_end_filter.js'), finalCode);
    console.log('Build completed successfully!');
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

build();
