const esbuild = require('esbuild');
const babel = require('@babel/core');
const fs = require('fs');
const path = require('path');

async function build() {
  console.log('Building extension...');

  try {
    // Hotfix for @looker/sdk type-only export bug in ES modules
    const sdkEsmIndex = path.join(__dirname, 'node_modules/@looker/sdk/lib/esm/index.js');
    if (fs.existsSync(sdkEsmIndex)) {
      let content = fs.readFileSync(sdkEsmIndex, 'utf8');
      if (content.includes("export { ILooker40SDK } from './4.0/methodsInterface';")) {
        console.log('Patching @looker/sdk ESM to remove empty interface export...');
        content = content.replace("export { ILooker40SDK } from './4.0/methodsInterface';", "");
        fs.writeFileSync(sdkEsmIndex, content, 'utf8');
      }
    }
    const sdkCjsIndex = path.join(__dirname, 'node_modules/@looker/sdk/lib/index.js');
    if (fs.existsSync(sdkCjsIndex)) {
      let content = fs.readFileSync(sdkCjsIndex, 'utf8');
      if (content.includes('return _methodsInterface.ILooker40SDK;')) {
        console.log('Patching @looker/sdk CJS to remove empty interface export...');
        content = content.replace('return _methodsInterface.ILooker40SDK;', 'return undefined;');
        fs.writeFileSync(sdkCjsIndex, content, 'utf8');
      }
    }

    // 1. Bundle with esbuild targeting es2015
    const result = await esbuild.build({
      entryPoints: [path.join(__dirname, 'src/index.tsx')],
      bundle: true,
      write: false, // get output in memory
      minify: false, // don't minify yet so we can run Babel easily
      target: 'es2015',
      outfile: 'month_end_filter.js',
      define: {
        'process.env.NODE_ENV': '"production"',
      },
    });

    if (!result.outputFiles || result.outputFiles.length === 0) {
      throw new Error('No output files generated by esbuild.');
    }

    const originalCode = result.outputFiles[0].text;

    // 2. Run Babel to transpile any ES6/ESNext syntax (like spreads) down to ES5
    console.log('Transpiling with Babel to remove spread operators...');
    const babelResult = await babel.transformAsync(originalCode, {
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              ie: '11', // Forces ES5 compliance
            },
            modules: false,
          },
        ],
      ],
      compact: false,
    });

    let finalCode = babelResult.code;

    // 3. Minify the transpiled ES5 code
    console.log('Minifying with esbuild targeting es5...');
    const minified = await esbuild.transform(finalCode, {
      minify: true,
      target: 'es5',
    });
    finalCode = minified.code;

    // 4. Verify no spread operators remain in the output
    const containsSpread = /\.\.\.[a-zA-Z_$0-9\[\{]/.test(finalCode);
    if (containsSpread) {
      console.warn('WARNING: Spread operator (...) detected in the output bundle!');
      const matches = finalCode.match(/(\S{0,20}\.\.\.\S{0,20})/g);
      console.warn('Potential matches:', matches);
      process.exit(1);
    } else {
      console.log('Success: No spread operators detected in the output bundle.');
    }

    fs.writeFileSync(path.join(__dirname, 'month_end_filter.js'), finalCode);
    console.log('Build completed successfully!');
  } catch (error) {
    console.error('Build failed:', error);
    process.exit(1);
  }
}

build();
